const quotes = [
  "Believe you can and you're halfway there.",
  "The only way to do great work is to love what you do.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Strive not to be a success, but rather to be of value.",
  "The best way to predict the future is to create it.",
  "Innovation distinguishes between a leader and a follower.",
  "The mind is everything. What you think you become.",
  "Everything you’ve ever wanted is on the other side of fear.",
  "Limitations live only in our minds.",
  "The only true wisdom is in knowing you know nothing.",
  "You are never too old to set another goal or to dream a new dream.",
  "To live is the rarest thing in the world. Most people just exist.",
  "The unexamined life is not worth living.",
  "Where there is love there is life.",
  "Life is what happens when you're busy making other plans.",
  "Get busy living or get busy dying.",
  "Twenty years from now you will be more disappointed by the things that you didn’t do than by the ones you did do.",
  "The only impossible journey is the one you never begin.",
  "The best revenge is massive success.",
  "Your time is limited, don't waste it living someone else's life.",
  "If you want to lift yourself up, lift up someone else.",
  "The journey of a thousand miles begins with a single step.",
  "The only thing necessary for the triumph of evil is for good men to do nothing.",
  "Imagination is more important than knowledge.",
  "It is during our darkest moments that we must focus to see the light.",
  "Don't let yesterday take up too much of today.",
  "We may encounter many defeats but we must not be defeated.",
  "The only way to do great work is to love what you do.",
  "If you can dream it, you can achieve it.",
  "The secret of getting ahead is getting started.",
  "The only place where success comes before work is in the dictionary.",
  "Action is the foundational key to all success.",
  "The best preparation for tomorrow is doing your best today.",
  "Happiness is not something ready-made. It comes from your own actions.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "It always seems impossible until it's done.",
  "With the new day comes new strength and new thoughts.",
  "The struggle you're in today is developing the strength you need for tomorrow.",
  "You are stronger than you think.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The future depends on what you do today.",
  "Keep your eyes on the stars, and your feet on the ground.",
  "If opportunity doesn't knock, build a door.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Change your thoughts and you change your world.",
  "The best way to find yourself is to lose yourself in the service of others.",
  "The only true wisdom is in knowing you know nothing.",
  "Live as if you were to die tomorrow. Learn as if you were to live forever.",
  "The mind is not a vessel to be filled, but a fire to be kindled.",
  "We cannot solve our problems with the same thinking we used when we created them.",
  "The measure of who we are is what we do with what we have.",
  "The only thing standing between you and your dream is the will to try and the belief that it is actually possible.",
  "Don't count the days, make the days count.",
  "The best way to appreciate your job is to imagine yourself without one.",
  "If you want to conquer fear, don't sit home and think about it. Go out and get busy.",
  "The only person you are destined to become is the person you decide to be.",
  "It's not whether you get knocked down, it's whether you get up.",
  "You miss 100% of the shots you don't take.",
  "The power of imagination makes us infinite.",
  "Every moment is a fresh beginning.",
  "The only thing that stands between a man and what he wants from life is often merely the will to try it and the faith to believe that it is possible.",
  "The best way out is always through.",
  "Happiness is a choice. You can choose to be happy. There's going to be stress in life, but it's your choice whether you let it affect you or not.",
  "The greatest wealth is health.",
  "The only true wisdom is in knowing you know nothing.",
  "Do not go where the path may lead, go instead where there is no path and leave a trail.",
  "The only way to do great work is to love what you do.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "The only thing that overcomes hard luck is hard work.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "If you want to achieve greatness stop asking for permission.",
  "The only true wisdom is in knowing you know nothing.",
  "The only person you are destined to become is the person you decide to be.",
  "The best way to predict the future is to create it.",
  "The only way to do great work is to love what you do.",
  "The mind is everything. What you think you become.",
  "Everything you’ve ever wanted is on the other side of fear.",
  "Limitations live only in our minds.",
  "The only true wisdom is in knowing you know nothing.",
  "You are never too old to set another goal or to dream a new dream.",
  "To live is the rarest thing in the world. Most people just exist.",
  "The unexamined life is not worth living.",
  "Where there is love there is life.",
  "Life is what happens when you're busy making other plans.",
  "Get busy living or get busy dying.",
  "Twenty years from now you will be more disappointed by the things that you didn’t do than by the ones you did do.",
  "The only impossible journey is the one you never begin.",
  "The best revenge is massive success.",
  "Your time is limited, don't waste it living someone else's life.",
  "If you want to lift yourself up, lift up someone else.",
  "The journey of a thousand miles begins with a single step.",
  "The only thing necessary for the triumph of evil is for good men to do nothing.",
  "Imagination is more important than knowledge.",
  "It is during our darkest moments that we must focus to see the light.",
  "Don't let yesterday take up too much of today.",
  "We may encounter many defeats but we must not be defeated.",
  "The only way to do great work is to love what you do.",
  "If you can dream it, you can achieve it.",
  "The secret of getting ahead is getting started.",
  "The only place where success comes before work is in the dictionary.",
  "Action is the foundational key to all success.",
];

// const checkused = new set();
// const quoteEl = document.querySelector("p");

// function generate() {
//   quoteEl.innerHTML = "hi";
// }

let log = Math.floor(Math.random() * 101);

function generate() {
  let dispaly = document.getElementsByTagName("p")[0];

  dispaly.innerHTML = quotes[log];
}
console.log(quotes[4]);
